baseURL = "http://help.macc.fct.pt/"
languageCode = "pt-pt"
title = "MACC"
theme = "hugo-theme-learn"

[params]
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true
  timezone = "Europe/Lisbon"
  themeVariant = "macc"
  bobSupport = "bob@support.macc.fct.pt"
  bobAccounts = "accounts@support.macc.fct.pt"

[outputs]
home = [ "HTML", "RSS", "JSON"]
